# Generated by Django 3.2 on 2025-02-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250205_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default='EMP0001', help_text="Employee identification number. Default: 'EMP0001'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='enterprise_id',
            field=models.CharField(default='default_enterprise_id', help_text="A unique identifier for the employee. Default: 'default_enterprise_id'.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='John', help_text="Employee's first name. Default: 'John'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_office',
            field=models.CharField(default='Headquarters', help_text="The home office location of the employee. Default: 'Headquarters'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Doe', help_text="Employee's last name. Default: 'Doe'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_address',
            field=models.EmailField(default='default@example.com', help_text="Employee's email address. Default: 'default@example.com'.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='management_level',
            field=models.IntegerField(default=1, help_text='The management level of the employee. Default: 1.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Employee', help_text="Employee's role within the company. Default: 'Employee'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='talent_segment',
            field=models.CharField(default='General', help_text="The talent segment the employee belongs to. Default: 'General'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams the employee belongs to. (No default value is set for ManyToMany fields.)', to='base.Team'),
        ),
    ]
