# Generated by Django 3.2 on 2025-02-05 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20250205_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'T_employee', 'verbose_name_plural': 'T_employees'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'M_project', 'verbose_name_plural': 'M_projects'},
        ),
        migrations.AlterModelOptions(
            name='projecthistory',
            options={'verbose_name': 'T_project history', 'verbose_name_plural': 'T_project historys'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'M_skill', 'verbose_name_plural': 'M_skills'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'M_team', 'verbose_name_plural': 'M_teams'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'M_training', 'verbose_name_plural': 'M_trainings'},
        ),
        migrations.AlterModelOptions(
            name='traininghistory',
            options={'verbose_name': 'T_training history', 'verbose_name_plural': 'T_training historys'},
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation date.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default='EMP0001', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='enterprise_id',
            field=models.CharField(default='default_enterprise_id', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_office',
            field=models.CharField(default='Headquarters', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_address',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='management_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='talent_segment',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(blank=True, to='base.Team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='training',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='period_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traininghistory',
            name='attend_date',
            field=models.DateTimeField(help_text='The date and time when the employee attended the training.'),
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(help_text='The date and time when the employee registered for this skill.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation date.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.skill')),
            ],
            options={
                'verbose_name': 'T_skill history',
                'verbose_name_plural': 'T_skill historys',
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('hire_date', models.DateTimeField()),
                ('retire_date', models.DateTimeField()),
                ('experience', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
            options={
                'verbose_name': 'T_background',
                'verbose_name_plural': 'T_backgrounds',
            },
        ),
    ]
