# Generated by Django 3.2 on 2025-02-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_employee_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_image',
        ),
    ]
