# Generated by Django 3.2 on 2025-02-05 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation date.'),
        ),
        migrations.AlterField(
            model_name='background',
            name='experience',
            field=models.TextField(help_text='Employee experience details.'),
        ),
        migrations.AlterField(
            model_name='background',
            name='hire_date',
            field=models.DateTimeField(help_text='The date and time the employee was hired.'),
        ),
        migrations.AlterField(
            model_name='background',
            name='retire_date',
            field=models.DateTimeField(help_text='The date and time the employee retired.'),
        ),
    ]
