# Generated by Django 3.2 on 2025-02-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20250205_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthistory',
            options={'verbose_name': 'T_project history', 'verbose_name_plural': 'T_project histories'},
        ),
        migrations.AlterModelOptions(
            name='skillhistory',
            options={'verbose_name': 'T_skill history', 'verbose_name_plural': 'T_skill historiess'},
        ),
        migrations.AlterModelOptions(
            name='traininghistory',
            options={'verbose_name': 'T_training history', 'verbose_name_plural': 'T_training histories'},
        ),
    ]
